import { supabase } from '../lib/supabase'

// Get all forms for the logged-in user, with submission count
export const getForms = async () => {
  const { data, error } = await supabase
    .from('forms')
    .select('*, submissions(count)')
    .order('created_at', { ascending: false })
  if (error) throw error
  return data
}

// Get a single form by its token
export const getFormByToken = async (token) => {
  const { data, error } = await supabase
    .from('forms')
    .select('*')
    .eq('token', token)
    .single()
  if (error) throw error
  return data
}

// Create a new form — token is auto-generated by Supabase (uuid default)
export const createForm = async ({ name, notification_email, email_notifications = true, spam_protection = true }) => {
  const { data: { user } } = await supabase.auth.getUser()
  
  // Fallback to the user's own email if no notification email provided
  const emailToUse = notification_email || user.email

  const { data, error } = await supabase
    .from('forms')
    .insert({ 
      name, 
      user_id: user.id, 
      notification_email: emailToUse,
      email_notifications,
      spam_protection
    })
    .select()
    .single()
  if (error) throw error
  return data
}

// Update any fields on a form
export const updateForm = async (token, updates) => {
  const { data, error } = await supabase
    .from('forms')
    .update(updates)
    .eq('token', token)
    .select()
    .single()
  if (error) throw error
  return data
}

// Delete a form and all its submissions (cascade handled by DB)
export const deleteForm = async (token) => {
  const { error } = await supabase
    .from('forms')
    .delete()
    .eq('token', token)
  if (error) throw error
}
